// build-config.js
// Runs during Netlify build. Reads environment variables and writes js/config.js.
// This file IS committed to Git. js/config.js is NOT (add it to .gitignore).

const fs   = require('fs');
const path = require('path');

// ── Required variables ────────────────────────────────────────────────────────
const required = ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'TICKET_API_URL', 'ADMIN_TOKEN'];

const missing = required.filter(key => !process.env[key]);
if (missing.length) {
  console.error('❌  Missing required environment variables:', missing.join(', '));
  console.error('    Set them in Netlify → Site Settings → Environment Variables.');
  process.exit(1);
}

// ── Validate TICKET_API_URL looks like a Supabase Edge Function URL ───────────
const apiUrl = process.env.TICKET_API_URL;
if (!apiUrl.startsWith('https://')) {
  console.error('❌  TICKET_API_URL must start with https://');
  process.exit(1);
}

// ── Write js/config.js ────────────────────────────────────────────────────────
// NOTE: This file is intentionally excluded from Git via .gitignore.
//       Never commit js/config.js — it contains secrets.
const content = `// Auto-generated by build-config.js — do not edit manually.
// This file is excluded from Git. See build-config.js for how it is generated.
var SUPABASE_URL      = "${process.env.SUPABASE_URL}";
var SUPABASE_ANON_KEY = "${process.env.SUPABASE_ANON_KEY}";
var TICKET_API_URL    = "${process.env.TICKET_API_URL}";
var ADMIN_TOKEN       = "${process.env.ADMIN_TOKEN}";
`;

fs.mkdirSync(path.join(__dirname, 'js'), { recursive: true });
fs.writeFileSync(path.join(__dirname, 'js', 'config.js'), content);
console.log('✅  js/config.js generated successfully.');

// ── Remind developer about CORS ───────────────────────────────────────────────
console.log('ℹ️   Reminder: your Supabase Edge Function must return these CORS headers:');
console.log('    Access-Control-Allow-Origin: *');
console.log('    Access-Control-Allow-Headers: content-type, x-admin-token');
console.log('    Access-Control-Allow-Methods: POST, OPTIONS');