// build-config.js
// Runs during Netlify build. Reads environment variables and writes js/config.js.
// This file IS committed to Git. js/config.js is NOT.

const fs   = require('fs');
const path = require('path');

const required = ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'TICKET_API_URL', 'ADMIN_TOKEN'];

const missing = required.filter(key => !process.env[key]);
if (missing.length) {
  console.error('❌  Missing required environment variables:', missing.join(', '));
  console.error('    Set them in Netlify → Site Settings → Environment Variables.');
  process.exit(1);
}

const content = `// Auto-generated by build-config.js — do not edit manually.
var SUPABASE_URL      = "${process.env.SUPABASE_URL}";
var SUPABASE_ANON_KEY = "${process.env.SUPABASE_ANON_KEY}";
var TICKET_API_URL    = "${process.env.TICKET_API_URL}";
var ADMIN_TOKEN       = "${process.env.ADMIN_TOKEN}";
`;

fs.mkdirSync(path.join(__dirname, 'js'), { recursive: true });
fs.writeFileSync(path.join(__dirname, 'js', 'config.js'), content);
console.log('✅  js/config.js generated successfully.');